import {readSettings,writeSettings,DEFAULT_SETTINGS,validateSettings} from './settings.js';
const KEY='assetbench.thumbnail-presets.v1';
export function mountPresets(page,changed,notice,busy){
  const panel=document.createElement('fieldset');panel.className='tm-presets';panel.innerHTML=`<legend>Saved looks</legend><label class="tm-field"><span>Preset</span><select data-preset><option value="studio">Studio</option><option value="cutout">Transparent + shadow</option><option value="dramatic">Dark showcase</option></select></label><div class="tm-preset-row"><input data-name type="text" maxlength="48" placeholder="Name this look" aria-label="Preset name"><button type="button" class="tm-btn tm-btn--secondary" data-save>Save</button></div><div class="tm-preset-row"><button type="button" class="tm-btn tm-btn--secondary" data-delete>Delete</button><button type="button" class="tm-btn tm-btn--secondary" data-export>Export</button><button type="button" class="tm-btn tm-btn--secondary" data-import>Import</button><input type="file" accept=".json" data-file hidden></div><p class="tm-tip">Saved on this browser. Export to share.</p>`;
  page.querySelector('.tm-controls').insertBefore(panel,page.querySelector('.tm-controls fieldset'));
  const q=s=>panel.querySelector(s),select=q('[data-preset]');let custom=[];
  try{custom=JSON.parse(localStorage.getItem(KEY)||'[]').slice(0,20).map(p=>({name:String(p.name).slice(0,48),settings:validateSettings(p.settings)}));}catch{custom=[];}
  const builtins={studio:DEFAULT_SETTINGS,cutout:{...DEFAULT_SETTINGS,mode:'transparent',shadow:true},dramatic:{...DEFAULT_SETTINGS,lighting:'dramatic',colour:'#080a10',exposure:1.2}};
  function refresh(){select.querySelectorAll('[data-custom]').forEach(x=>x.remove());custom.forEach((p,i)=>{const o=document.createElement('option');o.dataset.custom='';o.value='custom-'+i;o.textContent=p.name;select.append(o);});q('[data-delete]').disabled=!select.value.startsWith('custom-');}
  function persist(){localStorage.setItem(KEY,JSON.stringify(custom));refresh();}
  select.onchange=()=>{if(busy())return;const s=builtins[select.value]||custom[Number(select.value.split('-')[1])]?.settings;if(s){writeSettings(page,s);changed(true);}refresh();};
  q('[data-save]').onclick=()=>{if(busy())return;const name=q('[data-name]').value.trim();if(!name)return notice('Give your preset a name.',true);try{const entry={name,settings:readSettings(page)},index=custom.findIndex(p=>p.name===name);if(index<0){if(custom.length>=20)throw Error('You can save up to 20 presets.');custom.push(entry);}else custom[index]=entry;persist();select.value='custom-'+custom.findIndex(p=>p.name===name);refresh();notice('Preset saved.');}catch(e){notice(e.message,true);}};
  q('[data-delete]').onclick=()=>{if(busy()||!select.value.startsWith('custom-'))return;custom.splice(Number(select.value.split('-')[1]),1);try{persist();select.value='studio';refresh();}catch(e){notice(e.message,true);}};
  q('[data-export]').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,presets:custom.length?custom:[{name:'Current look',settings:readSettings(page)}]},null,2)],{type:'application/json'});const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='assetbench-thumbnail-presets.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  q('[data-import]').onclick=()=>q('[data-file]').click();q('[data-file]').onchange=async()=>{try{if(busy())return;const file=q('[data-file]').files[0];if(!file)return;if(file.size>100000)throw Error('Preset file is too large.');const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.presets)||data.presets.length>20)throw Error('Invalid preset file.');const next=[...custom];for(const p of data.presets){if(typeof p.name!=='string'||!p.name.trim())throw Error('Preset needs a name.');const entry={name:p.name.trim().slice(0,48),settings:validateSettings(p.settings)},i=next.findIndex(x=>x.name===entry.name);if(i<0)next.push(entry);else next[i]=entry;}if(next.length>20)throw Error('Import would exceed 20 presets.');custom=next;persist();notice('Presets imported. Select one to apply it.');}catch(e){notice(e.message,true);}finally{q('[data-file]').value='';}};
  refresh();
}
